server:
  port: 0
spring:
  application:
    name: news-system
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: news
    password: password
    url: jdbc:postgresql://news-database:5432/news_db
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

cache:
  type: LRU
  capacity: 10