server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: ${service-lb-urls.users}
          predicates:
            - Path=/authenticate/**
          filters:
            - RewritePath=/authenticate(?<remaining>.*), /api/v1/auth${remaining}
        - id: users
          uri: ${service-lb-urls.users}
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<remaining>.*), /api/v1/users${remaining}
        - id: news
          uri: ${service-lb-urls.news}
          predicates:
            - Path=/news/**
          filters:
            - RewritePath=/news(?<remaining>.*), /api/v1/news${remaining}
        - id: news
          uri: ${service-lb-urls.news}
          predicates:
            - Path=/comment/**
          filters:
            - RewritePath=/comment(?<remaining>.*), /api/v1/comment${remaining}
        - id: news
          uri: ${service-lb-urls.news}
          predicates:
             - Path=/comments/**
          filters:
             - RewritePath=/comments(?<remaining>.*), /api/v1/comments${remaining}
        - id: news
          uri: ${service-lb-urls.news}
          predicates:
            - Path=/journalist/**
          filters:
             - RewritePath=/journalist(?<remaining>.*), /api/v1/journalist${remaining}
        - id: news
          uri: ${service-lb-urls.news}
          predicates:
            - Path=/full/**
          filters:
            - RewritePath=/full(?<remaining>.*), /api/v1/full${remaining}


service-lb-urls:
  users: lb://user-service
  news: lb://news-system

security:
  jwt:
    secret: ${JWT_SECRET:2F413F4428472B4B61645367566B5970337336763979244226452948404D6351}

